"""Build an ASS subtitle file that aligns with the mezzanine timeline.

Two caption modes:
- static: multi-word lines, each displayed for the full line duration.
- karaoke: per-word replacement — each `TranscriptWord` becomes its own Dialogue
  event at the word's start/end. Simpler and more reliable than libass `\\k` tags.

Timeline: xfade overlaps clips, so the mezzanine is shorter than the sum of clip
durations by `(n_clips - 1) * transition.duration_sec`. For each caption word at
source time `t` (in the original video), we shift to the reel span first
(`t - reel.start_sec`), then subtract the cumulative transition overlap that
accrues before `t`'s position on the mezzanine timeline.
"""

from __future__ import annotations

import logging
from pathlib import Path

from reelforge_core.io_utils import write_text_atomic
from reelforge_core.models import (
    AnalysisReport,
    CaptionStyle,
    ComposeConfig,
    RankedReel,
    TranscriptWord,
)

log = logging.getLogger(__name__)

EMPTY_ASS = """[Script Info]
; Generated by ReelForge (captions off / no transcript)
ScriptType: v4.00+
PlayResX: {w}
PlayResY: {h}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Inter,48,&H00FFFFFF,&H0000FFFF,&H00000000,&H00000000,1,0,0,0,100,100,0,0,1,3,0,2,40,40,160,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def _fmt_time(sec: float) -> str:
    """ASS time: H:MM:SS.cc (centiseconds)."""
    sec = max(0.0, sec)
    h = int(sec // 3600)
    sec -= h * 3600
    m = int(sec // 60)
    sec -= m * 60
    cs = int(round(sec * 100))
    s = cs // 100
    cs_only = cs % 100
    return f"{h}:{m:02d}:{s:02d}.{cs_only:02d}"


def _escape_text(text: str) -> str:
    """Escape literal `{` / `}` so ASS doesn't interpret them as tag delimiters."""
    return text.replace("\\", "\\\\").replace("{", r"\{").replace("}", r"\}")


def _alignment_for(position: str) -> int:
    return {"lower_third": 2, "centered": 5, "top": 8}[position]


def _header(width: int, height: int, style: CaptionStyle) -> str:
    alignment = _alignment_for(style.position)
    if style.position == "lower_third":
        margin_v = int(height * style.safe_margin_pct)
    elif style.position == "top":
        margin_v = int(height * 0.08)
    else:
        margin_v = 0
    return (
        "[Script Info]\n"
        "; Generated by ReelForge\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {width}\n"
        f"PlayResY: {height}\n"
        "ScaledBorderAndShadow: yes\n"
        "WrapStyle: 2\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        f"Style: Default,{style.font_family},{style.font_size_px},"
        f"{style.primary_color},{style.highlight_color},{style.outline_color},"
        "&H00000000,1,0,0,0,100,100,0,0,1,"
        f"{style.outline_width_px},0,{alignment},40,40,{margin_v},1\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, "
        "Effect, Text\n"
    )


def _event(start: float, end: float, text: str, *, layer: int = 0) -> str:
    return (
        f"Dialogue: {layer},{_fmt_time(start)},{_fmt_time(end)},Default,,0,0,0,,"
        f"{_escape_text(text)}\n"
    )


# ---------------------------------------------------------------------------
# Transcript slicing + mezzanine-time mapping
# ---------------------------------------------------------------------------


def words_in_reel(
    analysis: AnalysisReport, reel: RankedReel
) -> list[TranscriptWord]:
    if analysis.transcript is None:
        return []
    out: list[TranscriptWord] = []
    for seg in analysis.transcript.segments:
        if seg.end < reel.start_sec or seg.start > reel.end_sec:
            continue
        for w in seg.words:
            if w.end < reel.start_sec or w.start > reel.end_sec:
                continue
            out.append(w)
    return out


def _source_to_mezz_time(
    t: float, reel: RankedReel, analysis: AnalysisReport, xfade_dur: float
) -> float:
    """Map a source timestamp `t` into the mezzanine timeline.

    Scenes in the reel are concatenated with xfade overlaps: every transition
    "reclaims" `xfade_dur` from the timeline. Find which scene `t` falls in
    (by reel position), then subtract `position * xfade_dur` from the offset
    into the reel span.
    """
    local = t - reel.start_sec
    # Walk the reel's scenes and find the position of t
    cumulative = 0.0
    for position, scene_idx in enumerate(reel.scene_indices):
        scene = analysis.scenes[scene_idx]
        dur = scene.end_sec - scene.start_sec
        if scene.start_sec <= t <= scene.end_sec + 1e-6:
            offset_into_scene = max(0.0, t - scene.start_sec)
            # Subtract xfade from the cumulative of earlier transitions,
            # plus the half-overlap the current scene starts being drawn early by.
            return max(0.0, cumulative + offset_into_scene - position * xfade_dur)
        cumulative += dur
    # Fallback: clamp to reel span minus overlap.
    return max(
        0.0,
        local - max(0, len(reel.scene_indices) - 1) * xfade_dur,
    )


# ---------------------------------------------------------------------------
# Chunking static mode
# ---------------------------------------------------------------------------


def _chunk_words_to_lines(
    words: list[TranscriptWord], max_chars: int, max_lines: int
) -> list[list[TranscriptWord]]:
    """Greedy: pack words into lines; start a new event when a line limit is
    hit, max_lines is reached, or the gap to the next word exceeds 700ms."""
    GAP_BREAK_S = 0.7
    events: list[list[TranscriptWord]] = []
    current_event: list[TranscriptWord] = []
    current_line_chars = 0
    current_lines_count = 1

    for i, w in enumerate(words):
        word_text = w.word.strip() or w.word
        word_len = len(word_text)
        new_line_chars = (current_line_chars + 1 + word_len) if current_line_chars else word_len
        if current_line_chars and new_line_chars > max_chars:
            if current_lines_count >= max_lines:
                events.append(current_event)
                current_event = [w]
                current_line_chars = word_len
                current_lines_count = 1
            else:
                current_event.append(w)
                current_line_chars = word_len
                current_lines_count += 1
        else:
            current_event.append(w)
            current_line_chars = new_line_chars
        # Gap break to next word
        if i + 1 < len(words):
            gap = words[i + 1].start - w.end
            if gap > GAP_BREAK_S:
                events.append(current_event)
                current_event = []
                current_line_chars = 0
                current_lines_count = 1

    if current_event:
        events.append(current_event)
    return events


def _event_text(words: list[TranscriptWord], max_chars: int) -> str:
    """Emit the event text with `\\N` linebreaks at max_chars boundaries."""
    lines: list[str] = []
    current: list[str] = []
    current_len = 0
    for w in words:
        token = w.word.strip()
        if not token:
            continue
        addition = (1 + len(token)) if current else len(token)
        if current and current_len + addition > max_chars:
            lines.append(" ".join(current))
            current = [token]
            current_len = len(token)
        else:
            current.append(token)
            current_len += addition
    if current:
        lines.append(" ".join(current))
    return "\\N".join(lines)


# ---------------------------------------------------------------------------
# Public entrypoint
# ---------------------------------------------------------------------------


def build_captions(
    reel: RankedReel,
    analysis: AnalysisReport,
    config: ComposeConfig,
    reel_dir: Path,
) -> Path:
    """Produce `captions.ass` on disk. Always writes a valid ASS file.

    Prefers the user-edited transcript (see `transcript_store.load_override_sync`)
    when one exists for this asset.
    """
    out_path = reel_dir / "captions.ass"
    width, height = config.resolution

    mode = config.captions.mode
    effective_analysis = analysis
    try:
        from reelforge_core.transcript_store import load_override_sync

        override = load_override_sync(analysis.asset_id)
    except Exception:  # pragma: no cover
        override = None
    if override is not None:
        effective_analysis = analysis.model_copy(update={"transcript": override})

    if mode == "off" or effective_analysis.transcript is None:
        write_text_atomic(out_path, EMPTY_ASS.format(w=width, h=height))
        return out_path

    words = words_in_reel(effective_analysis, reel)
    if not words:
        write_text_atomic(out_path, EMPTY_ASS.format(w=width, h=height))
        return out_path

    xfade_dur = (
        config.transition.duration_sec if config.transition.kind != "cut" else 0.0
    )

    def _mt(t: float) -> float:
        return _source_to_mezz_time(t, reel, analysis, xfade_dur)

    buf = [_header(width, height, config.captions)]

    if mode == "karaoke":
        # One event per word; position identical (default Dialogue alignment).
        for w in words:
            start = _mt(w.start)
            end = _mt(w.end)
            if end <= start:
                end = start + 0.15
            buf.append(_event(start, end, w.word.strip()))
    else:
        # Static mode: group words into multi-line events.
        events = _chunk_words_to_lines(
            words, config.captions.max_chars_per_line, config.captions.max_lines
        )
        for ev in events:
            if not ev:
                continue
            start = _mt(ev[0].start)
            end = _mt(ev[-1].end)
            if end <= start:
                end = start + 0.3
            text = _event_text(ev, config.captions.max_chars_per_line)
            buf.append(_event(start, end, text))

    write_text_atomic(out_path, "".join(buf))
    return out_path
