"""Build an ASS subtitle file that aligns with the mezzanine timeline.

Two caption modes:
- static: multi-word lines, each displayed for the full line duration.
- karaoke: TikTok-style word highlight — words are grouped into short lines,
  the whole line stays on screen for its duration, and the currently-spoken
  word is re-colored via an inline override. Implemented as one Dialogue per
  word interval (each carrying the full line text) rather than libass `\\k`
  tags, which keeps the timing under our control and renders identically
  everywhere libass runs.

Timeline: xfade overlaps clips, so the mezzanine is shorter than the sum of clip
durations by `(n_clips - 1) * transition.duration_sec`. For each caption word at
source time `t` (in the original video), we shift to the reel span first
(`t - reel.start_sec`), then subtract the cumulative transition overlap that
accrues before `t`'s position on the mezzanine timeline.
"""

from __future__ import annotations

import logging
from pathlib import Path

from reelforge_core.io_utils import write_text_atomic
from reelforge_core.models import (
    AnalysisReport,
    CaptionStyle,
    ComposeConfig,
    RankedReel,
    TranscriptWord,
)

log = logging.getLogger(__name__)

EMPTY_ASS = """[Script Info]
; Generated by ReelForge (captions off / no transcript)
ScriptType: v4.00+
PlayResX: {w}
PlayResY: {h}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Inter,48,&H00FFFFFF,&H0000FFFF,&H00000000,&H00000000,1,0,0,0,100,100,0,0,1,3,0,2,40,40,160,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def _fmt_time(sec: float) -> str:
    """ASS time: H:MM:SS.cc (centiseconds)."""
    sec = max(0.0, sec)
    h = int(sec // 3600)
    sec -= h * 3600
    m = int(sec // 60)
    sec -= m * 60
    cs = int(round(sec * 100))
    s = cs // 100
    cs_only = cs % 100
    return f"{h}:{m:02d}:{s:02d}.{cs_only:02d}"


def _escape_text(text: str) -> str:
    """Escape literal `{` / `}` so ASS doesn't interpret them as tag delimiters."""
    return text.replace("\\", "\\\\").replace("{", r"\{").replace("}", r"\}")


def _alignment_for(position: str) -> int:
    return {"lower_third": 2, "centered": 5, "top": 8}[position]


def _header(width: int, height: int, style: CaptionStyle) -> str:
    alignment = _alignment_for(style.position)
    if style.position == "lower_third":
        margin_v = int(height * style.safe_margin_pct)
    elif style.position == "top":
        margin_v = int(height * 0.08)
    else:
        margin_v = 0
    return (
        "[Script Info]\n"
        "; Generated by ReelForge\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {width}\n"
        f"PlayResY: {height}\n"
        "ScaledBorderAndShadow: yes\n"
        "WrapStyle: 2\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        f"Style: Default,{style.font_family},{style.font_size_px},"
        f"{style.primary_color},{style.highlight_color},{style.outline_color},"
        "&H00000000,1,0,0,0,100,100,0,0,1,"
        f"{style.outline_width_px},0,{alignment},40,40,{margin_v},1\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, "
        "Effect, Text\n"
    )


def _event(start: float, end: float, text: str, *, layer: int = 0) -> str:
    return (
        f"Dialogue: {layer},{_fmt_time(start)},{_fmt_time(end)},Default,,0,0,0,,"
        f"{_escape_text(text)}\n"
    )


def _event_raw(start: float, end: float, text: str, *, layer: int = 0) -> str:
    """Like _event, but `text` may contain ASS override tags — the caller is
    responsible for escaping the literal tokens."""
    return (
        f"Dialogue: {layer},{_fmt_time(start)},{_fmt_time(end)},Default,,0,0,0,,"
        f"{text}\n"
    )


def _inline_color(ass_color: str) -> str:
    """Convert a style color (&HAABBGGRR) into an inline \\c override (&HBBGGRR&)."""
    hexpart = ass_color.strip().removeprefix("&H").removesuffix("&")
    return f"\\c&H{hexpart[-6:]}&"


# ---------------------------------------------------------------------------
# Transcript slicing + mezzanine-time mapping
# ---------------------------------------------------------------------------


def words_in_reel(
    analysis: AnalysisReport, reel: RankedReel
) -> list[TranscriptWord]:
    if analysis.transcript is None:
        return []
    out: list[TranscriptWord] = []
    for seg in analysis.transcript.segments:
        if seg.end < reel.start_sec or seg.start > reel.end_sec:
            continue
        for w in seg.words:
            if w.end < reel.start_sec or w.start > reel.end_sec:
                continue
            out.append(w)
    return out


# ---------------------------------------------------------------------------
# Chunking static mode
# ---------------------------------------------------------------------------


def _chunk_words_to_lines(
    words: list[TranscriptWord], max_chars: int, max_lines: int
) -> list[list[TranscriptWord]]:
    """Greedy: pack words into lines; start a new event when a line limit is
    hit, max_lines is reached, or the gap to the next word exceeds 700ms."""
    GAP_BREAK_S = 0.7
    events: list[list[TranscriptWord]] = []
    current_event: list[TranscriptWord] = []
    current_line_chars = 0
    current_lines_count = 1

    for i, w in enumerate(words):
        word_text = w.word.strip() or w.word
        word_len = len(word_text)
        new_line_chars = (current_line_chars + 1 + word_len) if current_line_chars else word_len
        if current_line_chars and new_line_chars > max_chars:
            if current_lines_count >= max_lines:
                events.append(current_event)
                current_event = [w]
                current_line_chars = word_len
                current_lines_count = 1
            else:
                current_event.append(w)
                current_line_chars = word_len
                current_lines_count += 1
        else:
            current_event.append(w)
            current_line_chars = new_line_chars
        # Gap break to next word
        if i + 1 < len(words):
            gap = words[i + 1].start - w.end
            if gap > GAP_BREAK_S:
                events.append(current_event)
                current_event = []
                current_line_chars = 0
                current_lines_count = 1

    if current_event:
        events.append(current_event)
    return events


def _event_text(words: list[TranscriptWord], max_chars: int) -> str:
    """Emit the event text with `\\N` linebreaks at max_chars boundaries."""
    lines: list[str] = []
    current: list[str] = []
    current_len = 0
    for w in words:
        token = w.word.strip()
        if not token:
            continue
        addition = (1 + len(token)) if current else len(token)
        if current and current_len + addition > max_chars:
            lines.append(" ".join(current))
            current = [token]
            current_len = len(token)
        else:
            current.append(token)
            current_len += addition
    if current:
        lines.append(" ".join(current))
    return "\\N".join(lines)


# ---------------------------------------------------------------------------
# Public entrypoint
# ---------------------------------------------------------------------------


def build_captions(
    reel: RankedReel,
    analysis: AnalysisReport,
    config: ComposeConfig,
    reel_dir: Path,
    end_trims: list[float] | None = None,
    clips: list | None = None,
) -> Path:
    """Produce `captions.ass` on disk. Always writes a valid ASS file.

    Prefers the user-edited transcript (see `transcript_store.load_override_sync`)
    when one exists for this asset.
    """
    out_path = reel_dir / "captions.ass"
    width, height = config.resolution

    mode = config.captions.mode
    effective_analysis = analysis
    try:
        from reelforge_core.transcript_store import load_override_sync

        override = load_override_sync(analysis.asset_id)
    except Exception:  # pragma: no cover
        override = None
    if override is not None:
        effective_analysis = analysis.model_copy(update={"transcript": override})

    if mode == "off" or effective_analysis.transcript is None:
        write_text_atomic(out_path, EMPTY_ASS.format(w=width, h=height))
        return out_path

    words = words_in_reel(effective_analysis, reel)
    if not words:
        write_text_atomic(out_path, EMPTY_ASS.format(w=width, h=height))
        return out_path

    xfade_dur = (
        config.transition.duration_sec if config.transition.kind != "cut" else 0.0
    )

    # Build the source→mezzanine mapping from the ACTUAL rendered shot list.
    # Every shot occupies mezzanine time; only video shots map back to a span
    # of source footage, so an inserted photo simply pushes later captions
    # later. When `clips` isn't supplied the shot list is reconstructed from
    # the reel's scenes: clip_bounds folds in user trims + speech-safe
    # snapping (against the ORIGINAL transcript — the one clip extraction
    # saw) and `end_trims` carries the beat-sync shortenings.
    # (src_start, src_end, duration) — src bounds are None for photo shots.
    shots: list[tuple[float | None, float | None, float]] = []
    if clips is not None:
        for c in clips:
            if c.is_photo:
                shots.append((None, None, c.duration))
            else:
                shots.append((c.in_ts, c.out_ts, c.duration))
    else:
        from reelforge_core.compose.clips import clip_bounds

        n = len(reel.scene_indices)
        for position, idx in enumerate(reel.scene_indices):
            scene = analysis.scenes[idx]
            s, e = clip_bounds(position, n, scene, config, analysis)
            if end_trims is not None and position < n - 1 and position < len(end_trims):
                e = max(s + 0.5, e - end_trims[position])
            shots.append((s, e, e - s))

    segments_map: list[tuple[float, float, float]] = []  # (src_start, src_end, mezz_start)
    cum = 0.0
    for position, (src_start, src_end, dur) in enumerate(shots):
        if src_start is not None and src_end is not None:
            segments_map.append((src_start, src_end, cum - position * xfade_dur))
        cum += dur

    def _mt(t: float) -> float | None:
        for s, e, mezz_start in segments_map:
            if s <= t <= e + 1e-6:
                return max(0.0, mezz_start + (t - s))
        return None

    words = [w for w in words if _mt((w.start + w.end) / 2.0) is not None]
    if not words:
        write_text_atomic(out_path, EMPTY_ASS.format(w=width, h=height))
        return out_path

    def _mtw(t: float, w: TranscriptWord) -> float:
        """Map `t`, falling back to the word's midpoint (guaranteed mapped —
        words whose midpoints don't map were filtered above)."""
        v = _mt(t)
        if v is None:
            v = _mt((w.start + w.end) / 2.0)
        return v if v is not None else 0.0

    buf = [_header(width, height, config.captions)]

    if mode == "karaoke":
        # TikTok-style word highlight: group words into short single lines;
        # the full line stays visible for its whole duration and each word
        # gets an inline color override while it's being spoken. One Dialogue
        # per word interval — event k ends exactly when event k+1 starts, so
        # the line never flickers.
        highlight = _inline_color(config.captions.highlight_color)
        chunks = _chunk_words_to_lines(
            words, config.captions.karaoke_max_chars, max_lines=1
        )
        for chunk in chunks:
            cw = [w for w in chunk if w.word.strip()]
            if not cw:
                continue
            tokens = [_escape_text(w.word.strip()) for w in cw]
            for k, w in enumerate(cw):
                # First event starts at the line's first word; middle events
                # hand off at the NEXT word's start so pauses inside the line
                # hold the current highlight instead of dropping the caption.
                start = _mtw(cw[0].start, cw[0]) if k == 0 else _mtw(w.start, w)
                end = (
                    _mtw(cw[k + 1].start, cw[k + 1])
                    if k + 1 < len(cw)
                    else _mtw(cw[-1].end, cw[-1])
                )
                if end <= start:
                    end = start + 0.15
                line = " ".join(
                    f"{{{highlight}\\b1}}{tok}{{\\r}}" if j == k else tok
                    for j, tok in enumerate(tokens)
                )
                buf.append(_event_raw(start, end, line))
    else:
        # Static mode: group words into multi-line events.
        events = _chunk_words_to_lines(
            words, config.captions.max_chars_per_line, config.captions.max_lines
        )
        for ev in events:
            if not ev:
                continue
            start = _mtw(ev[0].start, ev[0])
            end = _mtw(ev[-1].end, ev[-1])
            if end <= start:
                end = start + 0.3
            text = _event_text(ev, config.captions.max_chars_per_line)
            buf.append(_event(start, end, text))

    write_text_atomic(out_path, "".join(buf))
    return out_path
