"""Build an ASS subtitle file that aligns with the mezzanine timeline.

Two caption modes:
- static: multi-word lines, each displayed for the full line duration.
- karaoke: TikTok-style word highlight — words are grouped into short lines,
  the whole line stays on screen for its duration, and the currently-spoken
  word is re-colored via an inline override. Implemented as one Dialogue per
  word interval (each carrying the full line text) rather than libass `\\k`
  tags, which keeps the timing under our control and renders identically
  everywhere libass runs.

Timeline: xfade overlaps clips, so the mezzanine is shorter than the sum of clip
durations by `(n_clips - 1) * transition.duration_sec`. For each caption word at
source time `t` (in the original video), we shift to the reel span first
(`t - reel.start_sec`), then subtract the cumulative transition overlap that
accrues before `t`'s position on the mezzanine timeline.
"""

from __future__ import annotations

import logging
from pathlib import Path

from reelforge_core.io_utils import write_text_atomic
from reelforge_core.models import (
    AnalysisReport,
    CaptionStyle,
    ComposeConfig,
    RankedReel,
    Transcript,
    TranscriptWord,
)

log = logging.getLogger(__name__)

EMPTY_ASS = """[Script Info]
; Generated by ReelForge (captions off / no transcript)
ScriptType: v4.00+
PlayResX: {w}
PlayResY: {h}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Inter,48,&H00FFFFFF,&H0000FFFF,&H00000000,&H00000000,1,0,0,0,100,100,0,0,1,3,0,2,40,40,160,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def _fmt_time(sec: float) -> str:
    """ASS time: H:MM:SS.cc (centiseconds)."""
    sec = max(0.0, sec)
    h = int(sec // 3600)
    sec -= h * 3600
    m = int(sec // 60)
    sec -= m * 60
    cs = int(round(sec * 100))
    s = cs // 100
    cs_only = cs % 100
    return f"{h}:{m:02d}:{s:02d}.{cs_only:02d}"


def _escape_text(text: str) -> str:
    """Escape literal `{` / `}` so ASS doesn't interpret them as tag delimiters."""
    return text.replace("\\", "\\\\").replace("{", r"\{").replace("}", r"\}")


def _alignment_for(position: str) -> int:
    return {"lower_third": 2, "centered": 5, "top": 8}[position]


def _header(width: int, height: int, style: CaptionStyle) -> str:
    alignment = _alignment_for(style.position)
    if style.position == "lower_third":
        margin_v = int(height * style.safe_margin_pct)
    elif style.position == "top":
        margin_v = int(height * 0.08)
    else:
        margin_v = 0
    return (
        "[Script Info]\n"
        "; Generated by ReelForge\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {width}\n"
        f"PlayResY: {height}\n"
        "ScaledBorderAndShadow: yes\n"
        "WrapStyle: 2\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        f"Style: Default,{style.font_family},{style.font_size_px},"
        f"{style.primary_color},{style.highlight_color},{style.outline_color},"
        "&H00000000,1,0,0,0,100,100,0,0,1,"
        f"{style.outline_width_px},0,{alignment},40,40,{margin_v},1\n"
        # Text overlays (editor). Size/color/alignment are overridden inline
        # per event; the style supplies font + a heavier outline + shadow.
        f"Style: Overlay,{style.font_family},84,&H00FFFFFF,&H00FFFFFF,"
        "&H00000000,&H80000000,1,0,0,0,100,100,0,0,1,4,1,5,60,60,0,1\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, "
        "Effect, Text\n"
    )


def _event(start: float, end: float, text: str, *, layer: int = 0) -> str:
    return (
        f"Dialogue: {layer},{_fmt_time(start)},{_fmt_time(end)},Default,,0,0,0,,"
        f"{_escape_text(text)}\n"
    )


def _event_raw(start: float, end: float, text: str, *, layer: int = 0) -> str:
    """Like _event, but `text` may contain ASS override tags — the caller is
    responsible for escaping the literal tokens."""
    return (
        f"Dialogue: {layer},{_fmt_time(start)},{_fmt_time(end)},Default,,0,0,0,,"
        f"{text}\n"
    )


def _inline_color(ass_color: str) -> str:
    """Convert a style color (&HAABBGGRR) into an inline \\c override (&HBBGGRR&)."""
    hexpart = ass_color.strip().removeprefix("&H").removesuffix("&")
    return f"\\c&H{hexpart[-6:]}&"


# ---------------------------------------------------------------------------
# Transcript slicing + mezzanine-time mapping
# ---------------------------------------------------------------------------


def words_in_reel(
    analysis: AnalysisReport, reel: RankedReel
) -> list[TranscriptWord]:
    if analysis.transcript is None:
        return []
    out: list[TranscriptWord] = []
    for seg in analysis.transcript.segments:
        if seg.end < reel.start_sec or seg.start > reel.end_sec:
            continue
        for w in seg.words:
            if w.end < reel.start_sec or w.start > reel.end_sec:
                continue
            out.append(w)
    return out


# ---------------------------------------------------------------------------
# Chunking static mode
# ---------------------------------------------------------------------------


def _chunk_words_to_lines(
    words: list[TranscriptWord], max_chars: int, max_lines: int
) -> list[list[TranscriptWord]]:
    """Greedy: pack words into lines; start a new event when a line limit is
    hit, max_lines is reached, or the gap to the next word exceeds 700ms."""
    GAP_BREAK_S = 0.7
    events: list[list[TranscriptWord]] = []
    current_event: list[TranscriptWord] = []
    current_line_chars = 0
    current_lines_count = 1

    for i, w in enumerate(words):
        word_text = w.word.strip() or w.word
        word_len = len(word_text)
        new_line_chars = (current_line_chars + 1 + word_len) if current_line_chars else word_len
        if current_line_chars and new_line_chars > max_chars:
            if current_lines_count >= max_lines:
                events.append(current_event)
                current_event = [w]
                current_line_chars = word_len
                current_lines_count = 1
            else:
                current_event.append(w)
                current_line_chars = word_len
                current_lines_count += 1
        else:
            current_event.append(w)
            current_line_chars = new_line_chars
        # Gap break to next word
        if i + 1 < len(words):
            gap = words[i + 1].start - w.end
            if gap > GAP_BREAK_S:
                events.append(current_event)
                current_event = []
                current_line_chars = 0
                current_lines_count = 1

    if current_event:
        events.append(current_event)
    return events


def _event_text(words: list[TranscriptWord], max_chars: int) -> str:
    """Emit the event text with `\\N` linebreaks at max_chars boundaries."""
    lines: list[str] = []
    current: list[str] = []
    current_len = 0
    for w in words:
        token = w.word.strip()
        if not token:
            continue
        addition = (1 + len(token)) if current else len(token)
        if current and current_len + addition > max_chars:
            lines.append(" ".join(current))
            current = [token]
            current_len = len(token)
        else:
            current.append(token)
            current_len += addition
    if current:
        lines.append(" ".join(current))
    return "\\N".join(lines)


# ---------------------------------------------------------------------------
# Public entrypoint
# ---------------------------------------------------------------------------


def _ass_color_to_inline(ass_color: str) -> str:
    hexpart = ass_color.strip().removeprefix("&H").removesuffix("&")
    return f"&H{hexpart[-6:]}&"


def _overlay_event(o, width: int, height: int, style: CaptionStyle) -> str:
    """One Dialogue line for a text overlay, drawn on layer 1 (above captions)."""
    an = {"top": 8, "center": 5, "bottom": 2}[o.position]
    if o.position == "top":
        margin_v = int(height * 0.08)
    elif o.position == "bottom":
        # Sit above the caption band so the two never collide.
        margin_v = int(height * style.safe_margin_pct) + int(style.font_size_px * 2.2)
    else:
        margin_v = 0
    fad = f"\\fad({max(0, o.fade_ms)},{max(0, o.fade_ms)})" if o.fade_ms > 0 else ""
    tags = (
        f"{{\\an{an}{fad}\\fs{max(12, o.font_size_px)}"
        f"\\c{_ass_color_to_inline(o.color)}\\3c{_ass_color_to_inline(o.outline_color)}"
        f"\\b{1 if o.bold else 0}}}"
    )
    text = _escape_text(o.text).replace("\r", "").replace("\n", "\\N")
    start = max(0.0, o.start_sec)
    end = max(start + 0.1, o.end_sec)
    return (
        f"Dialogue: 1,{_fmt_time(start)},{_fmt_time(end)},Overlay,,0,0,{margin_v},,"
        f"{tags}{text}\n"
    )


def _render_word_events(words: list[TranscriptWord], mt, config: ComposeConfig) -> list[str]:
    """Caption events for one run of words, in the configured mode. `mt` maps
    a word-local time to the mezzanine timeline."""
    out: list[str] = []
    if config.captions.mode == "karaoke":
        highlight = _inline_color(config.captions.highlight_color)
        chunks = _chunk_words_to_lines(words, config.captions.karaoke_max_chars, max_lines=1)
        for chunk in chunks:
            cw = [w for w in chunk if w.word.strip()]
            if not cw:
                continue
            tokens = [_escape_text(w.word.strip()) for w in cw]
            for k, w in enumerate(cw):
                start = mt(cw[0].start) if k == 0 else mt(w.start)
                end = mt(cw[k + 1].start) if k + 1 < len(cw) else mt(cw[-1].end)
                if end <= start:
                    end = start + 0.15
                line = " ".join(
                    f"{{{highlight}\\b1}}{tok}{{\\r}}" if j == k else tok
                    for j, tok in enumerate(tokens)
                )
                out.append(_event_raw(start, end, line))
    else:
        for ev in _chunk_words_to_lines(
            words, config.captions.max_chars_per_line, config.captions.max_lines
        ):
            if not ev:
                continue
            start = mt(ev[0].start)
            end = mt(ev[-1].end)
            if end <= start:
                end = start + 0.3
            out.append(_event(start, end, _event_text(ev, config.captions.max_chars_per_line)))
    return out


def build_captions(
    reel: RankedReel,
    analysis: AnalysisReport,
    config: ComposeConfig,
    reel_dir: Path,
    end_trims: list[float] | None = None,
    clips: list | None = None,
    analyses: "dict[str, AnalysisReport | None] | None" = None,
    overlays: list | None = None,
    xfades: list[float] | None = None,
    voiceover_captions: "list[tuple[object, Transcript]] | None" = None,
) -> Path:
    """Produce `captions.ass` on disk. Always writes a valid ASS file.

    The subtitle track carries two things: spoken-word captions (mapped from
    each shot's source transcript onto the mezzanine timeline) and editor
    text overlays (already in mezzanine seconds). Either may be empty.

    Shot geometry comes from `clips` when given (the ACTUAL rendered shot
    list — possibly mixing assets and photos) or is reconstructed from the
    reel's scenes. `xfades` is the per-cut crossfade duration list; a single
    reel-wide value is derived from config when omitted.

    Prefers user-edited transcripts (`transcript_store.load_override_sync`)
    per asset.
    """
    out_path = reel_dir / "captions.ass"
    width, height = config.resolution
    mode = config.captions.mode

    # Per-asset transcripts, with user overrides applied. Legacy single-asset
    # callers get {reel asset: analysis}.
    effective: dict[str, AnalysisReport | None] = dict(analyses or {})
    effective.setdefault(analysis.asset_id, analysis)
    try:
        from reelforge_core.transcript_store import load_override_sync

        for aid, rep in list(effective.items()):
            if rep is None:
                continue
            override = load_override_sync(aid)
            if override is not None:
                effective[aid] = rep.model_copy(update={"transcript": override})
    except Exception:  # pragma: no cover
        pass

    # ----- shot geometry: (asset_id, src_start, src_end, duration) -----
    shots: list[tuple[str | None, float | None, float | None, float]] = []
    if clips is not None:
        for c in clips:
            if c.is_photo or getattr(c, "speed", 1.0) != 1.0:
                # Photos map to no source span; sped shots are muted (v1 rule)
                # so their words are suppressed — both still advance mezz time.
                shots.append((None, None, None, c.duration))
            else:
                shots.append((c.asset_id or analysis.asset_id, c.in_ts, c.out_ts, c.duration))
    else:
        from reelforge_core.compose.clips import clip_bounds

        n = len(reel.scene_indices)
        for position, idx in enumerate(reel.scene_indices):
            scene = analysis.scenes[idx]
            s_, e_ = clip_bounds(
                position,
                n,
                scene,
                config,
                analysis,
                reel_start=reel.start_sec,
                reel_end=reel.end_sec,
            )
            if end_trims is not None and position < n - 1 and position < len(end_trims):
                e_ = max(s_ + 0.5, e_ - end_trims[position])
            shots.append((analysis.asset_id, s_, e_, e_ - s_))

    n_cuts = max(0, len(shots) - 1)
    if xfades is None:
        single = config.transition.duration_sec if config.transition.kind != "cut" else 0.04
        xfades = [single] * n_cuts
    xfades = list(xfades)[:n_cuts] + [0.0] * max(0, n_cuts - len(xfades))

    segments: list[tuple[str, float, float, float]] = []  # (asset, src_start, src_end, mezz_start)
    cum = 0.0
    reclaimed = 0.0
    for position, (aid, src_start, src_end, dur) in enumerate(shots):
        if position > 0:
            reclaimed += xfades[position - 1]
        if aid is not None and src_start is not None and src_end is not None:
            segments.append((aid, src_start, src_end, cum - reclaimed))
        cum += dur

    buf = [_header(width, height, config.captions)]
    caption_events: list[str] = []

    # ----- voiceover captions -----
    # Takes are already on the mezzanine timeline: a word at `w.start` in the
    # take sits at `take.start_sec + w.start`. While a take plays it owns the
    # caption band (footage audio is ducked beneath it), so footage words
    # inside any take's span are suppressed below.
    vo_spans: list[tuple[float, float]] = []
    total_len = cum
    if mode != "off":
        for take, transcript in (voiceover_captions or []):
            if transcript is None or getattr(take, "effective_gain", 1.0) <= 0:
                continue
            t0 = max(0.0, float(getattr(take, "start_sec", 0.0)))
            words = [
                w for seg in transcript.segments for w in seg.words
                if w.word.strip() and t0 + (w.start + w.end) / 2.0 <= total_len + 1e-6
            ]
            if not words:
                continue
            vo_spans.append((t0, t0 + max(w.end for w in words)))
            caption_events.extend(
                _render_word_events(words, lambda t, _t0=t0: max(0.0, _t0 + t), config)
            )

    def _covered(t: float) -> bool:
        return any(a - 1e-6 <= t <= b + 1e-6 for a, b in vo_spans)

    # ----- spoken-word captions, per segment -----
    if mode != "off":
        for aid, src_start, src_end, mezz_start in segments:
            rep = effective.get(aid)
            if rep is None or rep.transcript is None:
                continue
            seg_words: list[TranscriptWord] = []
            for seg in rep.transcript.segments:
                if seg.end < src_start or seg.start > src_end:
                    continue
                for w in seg.words:
                    mid = (w.start + w.end) / 2.0
                    if src_start <= mid <= src_end + 1e-6:
                        seg_words.append(w)
            def _mt(t: float, _ms: float = mezz_start, _ss: float = src_start) -> float:
                return max(0.0, _ms + (t - _ss))

            # Footage words under a voiceover take yield to the take's captions.
            seg_words = [w for w in seg_words if not _covered(_mt((w.start + w.end) / 2.0))]
            if not seg_words:
                continue
            caption_events.extend(_render_word_events(seg_words, _mt, config))

    # ----- text overlays (editor) -----
    overlay_events = [
        _overlay_event(o, width, height, config.captions)
        for o in (overlays or [])
        if o.text.strip() and o.end_sec > o.start_sec
    ]

    if not caption_events and not overlay_events:
        write_text_atomic(out_path, EMPTY_ASS.format(w=width, h=height))
        return out_path

    buf.extend(caption_events)
    buf.extend(overlay_events)
    write_text_atomic(out_path, "".join(buf))
    return out_path


def has_dialogue(ass_path: Path) -> bool:
    """True when the ASS file carries at least one event worth burning in."""
    try:
        return "Dialogue:" in ass_path.read_text(encoding="utf-8")
    except OSError:
        return False
