"""The scorecard end to end on a synthetic reel directory, plus the ASS parser
against the exact caption files the pipeline writes."""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest

from reelforge_core.qa.captions_geom import parse_ass
from reelforge_core.qa.scorecard import build_scorecard, format_scorecard, write_scorecard

# Verbatim header + events from a real render (the skimboard mix), so the
# parser is tested against what captions.py actually emits.
REAL_ASS = r"""[Script Info]
; Generated by ReelForge
ScriptType: v4.00+
PlayResX: 1080
PlayResY: 1920
ScaledBorderAndShadow: yes
WrapStyle: 2

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Inter,64,&H00FFFFFF,&H0000FFFF,&H00000000,&H00000000,1,0,0,0,100,100,0,0,1,4,0,2,40,40,288,1
Style: Overlay,Inter,84,&H00FFFFFF,&H00FFFFFF,&H00000000,&H80000000,1,0,0,0,100,100,0,0,1,4,1,5,60,60,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.78,0:00:03.08,Default,,0,0,0,,Going to make a quick video\Non how to
Dialogue: 1,0:00:00.40,0:00:02.80,Overlay,,0,0,153,,{\an8\fad(250,250)\fs84\c&HFFFFFF&\3c&H000000&\b1}Skater lines up the trick
Dialogue: 0,0:00:03.08,0:00:03.50,Default,,0,0,0,,{\c&H00FFFF&\b1}Stop{\r} overpaying
"""


def test_parser_reads_real_output_and_places_boxes(tmp_path: Path) -> None:
    path = tmp_path / "captions.ass"
    path.write_text(REAL_ASS)
    doc = parse_ass(path)
    assert (doc.width, doc.height) == (1080, 1920)
    lower, hook, lit = doc.boxes

    # Two lines of 64px sitting 288px above the bottom: they reach y≈1632,
    # deep inside the TikTok/Reels bottom UI band.
    assert lower.lines == 2 and lower.rect.y1 == pytest.approx(1920 - 288, abs=1)
    assert lower.rect.y0 < 1632 - 2 * 64

    # The hook: \an8 at the event's MarginV 153 -> top edge at y=153, above
    # the safe top of 290.
    assert hook.style == "Overlay" and hook.rect.y0 == pytest.approx(153, abs=1)
    assert hook.highlighted == []  # an overlay's colour tag is not a highlight

    assert lit.highlighted == ["Stop"] and lit.words == 2


def _write_reel(tmp_path: Path, *, shots: list[dict], words: list[dict], ass: str | None, duration: float):
    reel = tmp_path / "reel"
    reel.mkdir()
    (reel / "compose.json").write_text(json.dumps({
        "asset_id": "a", "reel_id": "r1", "reel_title": "Test reel",
        "duration_sec": duration, "width": 1080, "height": 1920,
        "style": "talking_head", "scene_clip_map": shots, "layers": [],
    }))
    (reel / "words.json").write_text(json.dumps({"words": words}))
    if ass is not None:
        (reel / "captions.ass").write_text(ass)
    return reel


def test_scorecard_scores_a_static_talking_head_as_failing_rhythm(tmp_path: Path) -> None:
    shots = [
        {"scene_index": 0, "in_ts": 0.0, "out_ts": 10.0, "duration": 10.0, "asset_id": "a",
         "punch_in": None, "transition_after": ["fade", 0.04]},
        {"scene_index": 0, "in_ts": 10.0, "out_ts": 20.0, "duration": 10.0, "asset_id": "a",
         "punch_in": None, "transition_after": None},
    ]
    words = [{"start": 1.2, "end": 1.5, "word": "Hey"}, {"start": 1.5, "end": 1.9, "word": "guys,"}]
    words += [{"start": 2.0 + i * 0.4, "end": 2.3 + i * 0.4, "word": "word"} for i in range(40)]
    words += [{"start": 18.5, "end": 18.9, "word": "so"}, {"start": 18.9, "end": 19.3, "word": "yeah"}]
    reel = _write_reel(tmp_path, shots=shots, words=words, ass=REAL_ASS, duration=20.0)

    card = build_scorecard(reel, loudness=False)
    by = {c["metric"]: c for c in card["checks"]}
    assert card["kind"] == "talking" and card["precise"] is True
    assert card["changes"] == []  # one continuous 20s shot split in two
    assert by["changes_per_min"]["result"] == "fail"
    assert by["longest_static_sec"]["value"] == 20.0
    assert by["hook_latency_sec"]["result"] == "fail"  # first word at 1.2s
    assert by["greeting"]["result"] == "fail"
    assert by["trailing_filler"]["result"] == "fail"
    assert by["safe_zone_violations"]["value"] >= 2  # lower caption + hook
    assert by["integrated_lufs"]["result"] == "n/a"  # loudness skipped
    assert "FAIL" in format_scorecard(card)


def test_scorecard_marks_old_manifests_as_estimates(tmp_path: Path) -> None:
    """Rendered before per-shot metadata: no durations/zoom, so every same-
    scene junction looks contiguous. Scored, but flagged."""
    shots = [{"scene_index": 0, "in_ts": 0.0, "out_ts": 5.0}, {"scene_index": 1, "in_ts": 9.0, "out_ts": 14.0}]
    reel = _write_reel(tmp_path, shots=shots, words=[], ass=None, duration=10.0)
    card = build_scorecard(reel, loudness=False)
    assert card["precise"] is False
    assert [c["why"] for c in card["changes"]] == ["jump"]  # 4s source skip still detected
    assert "estimated" in format_scorecard(card)


def test_missing_inputs_are_not_applicable_never_errors(tmp_path: Path) -> None:
    reel = tmp_path / "reel"
    reel.mkdir()
    (reel / "compose.json").write_text(json.dumps({"reel_id": "r", "duration_sec": 12.0, "scene_clip_map": []}))
    card = write_scorecard(reel, loudness=False)
    assert (reel / "qa.json").exists()
    assert card["kind"] == "action"
    assert all(c["result"] in ("pass", "fail", "n/a") for c in card["checks"])


@pytest.mark.skipif(not shutil.which("ffmpeg"), reason="ffmpeg not available")
def test_loudness_is_measured_from_the_mezzanine(tmp_path: Path) -> None:
    reel = _write_reel(tmp_path, shots=[], words=[], ass=None, duration=3.0)
    subprocess.run(
        ["ffmpeg", "-y", "-v", "error", "-f", "lavfi", "-i", "sine=frequency=440:duration=3",
         "-af", "volume=-20dB", "-ac", "2", str(reel / "mezzanine.mp4")],
        check=True,
    )
    card = build_scorecard(reel)
    by = {c["metric"]: c for c in card["checks"]}
    assert by["integrated_lufs"]["value"] is not None and by["integrated_lufs"]["value"] < -14
    assert by["true_peak_dbtp"]["value"] < 0
